// GENERATED by mobile/tools/tokens_from_css.ts from qvault/static/tokens.css. Do not edit by hand:
// change tokens.css and run `node tools/tokens_from_css.ts` in mobile/.
// tests/test_mobile_tokens.py fails when this file is out of date.

export type ColorTokens = {
  bg: string;
  bgSubtle: string;
  surface: string;
  surfaceRaised: string;
  fill: string;
  fillHover: string;
  fillActive: string;
  fillRaisedPressed: string;
  border: string;
  borderStrong: string;
  text: string;
  textMuted: string;
  textSubtle: string;
  textDisabled: string;
  fillDisabled: string;
  borderDisabled: string;
  accent: string;
  accentPressed: string;
  accentText: string;
  accentSubtle: string;
  accentBorder: string;
  accentFg: string;
  link: string;
  focus: string;
  selection: string;
  danger: string;
  dangerPressed: string;
  dangerText: string;
  markFilled: string;
  markEmpty: string;
  backdrop: string;
  chrome: {
    bg: string;
    bgRaised: string;
    border: string;
    text: string;
    textMuted: string;
    badgeBg: string;
    badgeText: string;
    dot: string;
  };
  status: {
    success: {
      fg: string;
      bg: string;
      border: string;
    };
    warning: {
      fg: string;
      bg: string;
      border: string;
    };
    critical: {
      fg: string;
      bg: string;
      border: string;
    };
    info: {
      fg: string;
      bg: string;
      border: string;
    };
    neutral: {
      fg: string;
      bg: string;
      border: string;
    };
  };
  shadow: string;
};

export const light: ColorTokens = {
  bg: '#F7F8FA',
  bgSubtle: '#F3F5F8',
  surface: '#FFFFFF',
  surfaceRaised: '#FFFFFF',
  fill: '#EFF1F5',
  fillHover: '#E7EAF0',
  fillActive: '#E1E5EC',
  fillRaisedPressed: '#EFF1F5',
  border: '#DDE1E9',
  borderStrong: '#7C8597',
  text: '#16233A',
  textMuted: '#4A5568',
  textSubtle: '#5F697C',
  textDisabled: '#7C8597',
  fillDisabled: '#EFF1F5',
  borderDisabled: '#DDE1E9',
  accent: '#2D60C3',
  accentPressed: '#2152B0',
  accentText: '#FFFFFF',
  accentSubtle: '#E7EFFF',
  accentBorder: '#9ABCF9',
  accentFg: '#234993',
  link: '#2D60C3',
  focus: '#2D60C3',
  selection: '#DAE7FF',
  danger: '#A82D20',
  dangerPressed: '#942318',
  dangerText: '#FFFFFF',
  markFilled: '#1B6B4F',
  markEmpty: '#7C8597',
  backdrop: '#0E172966',
  chrome: {
    bg: '#0E1729',
    bgRaised: '#1B2740',
    border: '#293552',
    text: '#EEF1F6',
    textMuted: '#93A0B8',
    badgeBg: '#EFBE77',
    badgeText: '#11161E',
    dot: '#8BB3FA',
  },
  status: {
    success: {
      fg: '#1B6B4F',
      bg: '#E8F2EC',
      border: '#B4D5C4',
    },
    warning: {
      fg: '#8A5A12',
      bg: '#FAF2E3',
      border: '#E7D3AA',
    },
    critical: {
      fg: '#A82D20',
      bg: '#FBEBE9',
      border: '#EEC2BC',
    },
    info: {
      fg: '#136782',
      bg: '#E5F3F8',
      border: '#AFD5E4',
    },
    neutral: {
      fg: '#4A5568',
      bg: '#EFF1F5',
      border: '#DDE1E9',
    },
  },
  shadow: '#0E1729',
};

export const dark: ColorTokens = {
  bg: '#11161E',
  bgSubtle: '#171C25',
  surface: '#171C25',
  surfaceRaised: '#1D232E',
  fill: '#1D232E',
  fillHover: '#232936',
  fillActive: '#29303E',
  fillRaisedPressed: '#29303E',
  border: '#313947',
  borderStrong: '#6A7385',
  text: '#EEF1F6',
  textMuted: '#B9C0CD',
  textSubtle: '#8891A1',
  textDisabled: '#6A7385',
  fillDisabled: '#1D232E',
  borderDisabled: '#313947',
  accent: '#376ACF',
  accentPressed: '#3F71D3',
  accentText: '#FFFFFF',
  accentSubtle: '#162542',
  accentBorder: '#2E5091',
  accentFg: '#8BB3FA',
  link: '#8BB3FA',
  focus: '#3F71D3',
  selection: '#1D3563',
  danger: '#C24339',
  dangerPressed: '#C64A40',
  dangerText: '#FFFFFF',
  markFilled: '#7BD3A9',
  markEmpty: '#6A7385',
  backdrop: '#05080DA3',
  chrome: {
    bg: '#171C25',
    bgRaised: '#232936',
    border: '#313947',
    text: '#EEF1F6',
    textMuted: '#8891A1',
    badgeBg: '#EFBE77',
    badgeText: '#11161E',
    dot: '#8BB3FA',
  },
  status: {
    success: {
      fg: '#7BD3A9',
      bg: '#122E21',
      border: '#235941',
    },
    warning: {
      fg: '#EFBE77',
      bg: '#342611',
      border: '#694D20',
    },
    critical: {
      fg: '#F89A8F',
      bg: '#401B18',
      border: '#813933',
    },
    info: {
      fg: '#88C9E2',
      bg: '#0E2C36',
      border: '#22576A',
    },
    neutral: {
      fg: '#B9C0CD',
      bg: '#232936',
      border: '#313947',
    },
  },
  shadow: '#05080D',
};

/** Durations in ms and easings as cubic-bezier control points, shared with the web. */
export const motionTokens = {
  press: 100,
  popover: 150,
  dialog: 220,
  dialogExit: 160,
  seal: 620,
  easeEnter: [0, 0, 0.38, 0.9],
  easeExit: [0.2, 0, 1, 0.9],
  easeStandard: [0.2, 0, 0.38, 0.9],
  easeSeal: [0.34, 1.36, 0.64, 1],
} as const;
