minimumReleaseAgeExclude:
  - '@expo/cli@57.0.17'
  - '@expo/fingerprint@0.20.9'
  - '@expo/local-build-cache-provider@57.0.7'
  - '@expo/metro-config@57.0.9'
  - '@expo/prebuild-config@57.0.13'
  - '@expo/router-server@57.0.7'
  - expo-asset@57.0.13
  - expo-constants@57.0.13
  - expo-file-system@57.0.5
  - expo-modules-core@57.0.12
  - expo-modules-jsi@57.0.5
  - expo@57.0.15
  - expo-updates@57.0.16
